In [239]:
import pandas as pd
import numpy as np

In [240]:
# Import raw data from csv.
df = pd.read_csv('./RawData.csv')
df.head()

,Unnamed: 0,Company name,Gearing (%)\n2018,Long Term Debt\nth GBP 2018,BvD Independence Indicator,Turnover\nth GBP 2017,Turnover\nth GBP 2016,Turnover\nth GBP 2015,Depreciation\nth GBP 2017,Depreciation\nth GBP 2016,Depreciation\nth GBP 2015,Total Assets\nth GBP 2018,Total Assets\nth GBP 2017,Total Assets\nth GBP 2016,Total Assets\nth GBP 2015,Fixed Assets\nth GBP 2017,Fixed Assets\nth GBP 2016,Fixed Assets\nth GBP 2015,Turnover (%)\n2017,Turnover (%)\n2016,Turnover (%)\n2015,EBITDA margin (%)\n2017,EBITDA margin (%)\n2016,EBITDA margin (%)\n2015
0,1.0,BP P.L.C.,120.95,"-44,221,000",B+,"180,877,000","151,245,000","150,982,000","12,006,000","9,817,000","11,048,000","216,474,000","201,410,000","212,946,000","175,564,000","145,968,000","157,983,000","127,740,000",19.59,0.17,-33.41,10.65,7.16,9.93
1,2.0,ROYAL DUTCH SHELL PLC,65.28,"-52,265,000",A+,"230,639,000","194,548,000","179,476,000","18,233,000","19,264,000","17,467,000","308,106,000","298,993,000","332,161,000","227,457,000","228,438,000","261,996,000","164,219,000",18.55,8.40,-33.54,15.52,14.08,10.86
2,3.0,GLENCORE PLC,113.59,"-20,708,000",A+,"151,957,000","123,965,000","115,489,000","3,644,000","5,511,000","7,848,000","100,840,000","100,276,000","100,989,000","87,032,000","63,502,000","65,803,000","58,448,000",22.58,7.34,-18.54,6.88,5.15,3.07
3,4.0,JACK RICHARDS HOLDINGS LIMITED,148.19,"-11,653",D,"45,971","40,779","35,683","4,089","3,868","3,315","43,423","33,841","34,002","31,156","21,990","23,817","21,153",12.73,14.28,5.02,13.08,13.84,14.32
4,5.0,TESCO PLC,233.35,"-10,114,000",A+,"55,917,000","54,433,000","62,284,000","1,331,000","1,095,000","5,409,000","44,862,000","45,853,000","43,904,000","44,214,000","30,436,000","29,076,000","32,256,000",2.73,-12.61,-2.00,4.73,4.75,0.07

In [241]:
# Replace weird null values with native numpy NaN.
df.replace(to_replace="n.a.", value=np.nan, inplace=True)
df.replace(to_replace="n.s.", value=np.nan, inplace=True)

df.isna().sum()

Unnamed: 0                       0
Company name                     0
Gearing (%)\n2018               47
Long Term Debt\nth GBP 2018     54
BvD Independence Indicator       0
Turnover\nth GBP 2017           36
Turnover\nth GBP 2016           49
Turnover\nth GBP 2015           96
Depreciation\nth GBP 2017       35
Depreciation\nth GBP 2016       49
Depreciation\nth GBP 2015       88
Total Assets\nth GBP 2018       41
Total Assets\nth GBP 2017       35
Total Assets\nth GBP 2016       49
Total Assets\nth GBP 2015       84
Fixed Assets\nth GBP 2017       35
Fixed Assets\nth GBP 2016       49
Fixed Assets\nth GBP 2015       84
Turnover (%)\n2017              57
Turnover (%)\n2016              99
Turnover (%)\n2015             972
EBITDA margin (%)\n2017        180
EBITDA margin (%)\n2016        208
EBITDA margin (%)\n2015        235
dtype: int64

In [242]:
# Drop unnecessary index column.
df.drop(['Unnamed: 0'], axis=1, inplace=True)
# Drop rows with NaN values.
df.dropna(inplace=True)
df.shape[0]

11852

In [243]:
# Rename columns.
ends = ["\nth GBP", "\n"]
for col in df.columns:
    for end in ends:
        if end in col:
            df.rename(columns={col: col.replace(end, "")}, inplace=True)

df.columns

Index(['Company name', 'Gearing (%)2018', 'Long Term Debt 2018',
       'BvD Independence Indicator', 'Turnover 2017', 'Turnover 2016',
       'Turnover 2015', 'Depreciation 2017', 'Depreciation 2016',
       'Depreciation 2015', 'Total Assets 2018', 'Total Assets 2017',
       'Total Assets 2016', 'Total Assets 2015', 'Fixed Assets 2017',
       'Fixed Assets 2016', 'Fixed Assets 2015', 'Turnover (%)2017',
       'Turnover (%)2016', 'Turnover (%)2015', 'EBITDA margin (%)2017',
       'EBITDA margin (%)2016', 'EBITDA margin (%)2015'],
      dtype='object')

In [244]:
# Print dtypes of columns.
df.dtypes

Company name                  object
Gearing (%)2018               object
Long Term Debt 2018           object
BvD Independence Indicator    object
Turnover 2017                 object
Turnover 2016                 object
Turnover 2015                 object
Depreciation 2017             object
Depreciation 2016             object
Depreciation 2015             object
Total Assets 2018             object
Total Assets 2017             object
Total Assets 2016             object
Total Assets 2015             object
Fixed Assets 2017             object
Fixed Assets 2016             object
Fixed Assets 2015             object
Turnover (%)2017              object
Turnover (%)2016              object
Turnover (%)2015              object
EBITDA margin (%)2017         object
EBITDA margin (%)2016         object
EBITDA margin (%)2015         object
dtype: object

In [245]:
# Get rid of commas in numerically formatted columns.
# Try to convert data to numeric, float if there is decimal point, integer otherwise.
for col in df.columns:
    df[col] = df[col].str.replace(',', '')
    try:
        df[col] = pd.to_numeric(df[col], errors='raise')
    except ValueError:
        pass

df.dtypes

Company name                   object
Gearing (%)2018               float64
Long Term Debt 2018             int64
BvD Independence Indicator     object
Turnover 2017                   int64
Turnover 2016                   int64
Turnover 2015                   int64
Depreciation 2017               int64
Depreciation 2016               int64
Depreciation 2015               int64
Total Assets 2018               int64
Total Assets 2017               int64
Total Assets 2016               int64
Total Assets 2015               int64
Fixed Assets 2017               int64
Fixed Assets 2016               int64
Fixed Assets 2015               int64
Turnover (%)2017              float64
Turnover (%)2016              float64
Turnover (%)2015              float64
EBITDA margin (%)2017         float64
EBITDA margin (%)2016         float64
EBITDA margin (%)2015         float64
dtype: object

In [246]:
df.isna().sum()

Company name                  0
Gearing (%)2018               0
Long Term Debt 2018           0
BvD Independence Indicator    0
Turnover 2017                 0
Turnover 2016                 0
Turnover 2015                 0
Depreciation 2017             0
Depreciation 2016             0
Depreciation 2015             0
Total Assets 2018             0
Total Assets 2017             0
Total Assets 2016             0
Total Assets 2015             0
Fixed Assets 2017             0
Fixed Assets 2016             0
Fixed Assets 2015             0
Turnover (%)2017              0
Turnover (%)2016              0
Turnover (%)2015              0
EBITDA margin (%)2017         0
EBITDA margin (%)2016         0
EBITDA margin (%)2015         0
dtype: int64

In [247]:
for col in df.columns:
    if "Turnover (%)" in col:
        df.rename(columns={col: col.replace("Turnover (%)", "Growth Opportunities ")}, inplace=True)
    elif "Gearing (%)" in col:
        df.rename(columns={col: col.replace("Gearing (%)", "Gearing ")}, inplace=True)
    elif "EBITDA margin (%)" in col:
        df.rename(columns={col: col.replace("EBITDA margin (%)", "Profitability ")}, inplace=True)
    elif "Turnover" in col:
        df[col] = np.log(df[col])
        df.rename(columns={col: col.replace("Turnover", "Size")}, inplace=True)


# Feature Engineering
years = ["2015", "2016", "2017"]

for year in years:
    # Non-debt tax shields proxy.
    df["NDTS " + year] = df["Depreciation " + year] / df["Total Assets " + year]
    df.drop(["Depreciation " + year], axis=1, inplace=True)
    # Asset Tangability.
    df["Asset Tangability " + year] = df["Fixed Assets " + year] / df["Total Assets " + year]
    df.drop(["Fixed Assets " + year], axis=1, inplace=True)
    df.drop(["Total Assets " + year], axis=1, inplace=True)

df["Gearing Long"] = abs(df["Long Term Debt 2018"]) / df["Total Assets 2018"] * 100
 

df.columns

Index(['Company name', 'Gearing 2018', 'Long Term Debt 2018',
       'BvD Independence Indicator', 'Size 2017', 'Size 2016', 'Size 2015',
       'Total Assets 2018', 'Growth Opportunities 2017',
       'Growth Opportunities 2016', 'Growth Opportunities 2015',
       'Profitability 2017', 'Profitability 2016', 'Profitability 2015',
       'NDTS 2015', 'Asset Tangability 2015', 'NDTS 2016',
       'Asset Tangability 2016', 'NDTS 2017', 'Asset Tangability 2017',
       'Gearing Long'],
      dtype='object')

In [248]:
df.head()

,Company name,Gearing 2018,Long Term Debt 2018,BvD Independence Indicator,Size 2017,Size 2016,Size 2015,Total Assets 2018,Growth Opportunities 2017,Growth Opportunities 2016,Growth Opportunities 2015,Profitability 2017,Profitability 2016,Profitability 2015,NDTS 2015,Asset Tangability 2015,NDTS 2016,Asset Tangability 2016,NDTS 2017,Asset Tangability 2017,Gearing Long
0,BP P.L.C.,120.95,-44221000,B+,19.013328,18.834412,18.832671,216474000,19.59,0.17,-33.41,10.65,7.16,9.93,0.062929,0.727598,0.046101,0.741892,0.059610,0.724731,20.427857
1,ROYAL DUTCH SHELL PLC,65.28,-52265000,A+,19.256364,19.086189,19.005552,308106000,18.55,8.40,-33.54,15.52,14.08,10.86,0.076793,0.721978,0.057996,0.788762,0.060981,0.764025,16.963318
2,GLENCORE PLC,113.59,-20708000,A+,18.839108,18.635510,18.564686,100840000,22.58,7.34,-18.54,6.88,5.15,3.07,0.090174,0.671569,0.054570,0.651586,0.036340,0.633272,20.535502
3,JACK RICHARDS HOLDINGS LIMITED,148.19,-11653,D,10.735766,10.615923,10.482430,43423,12.73,14.28,5.02,13.08,13.84,14.32,0.106400,0.678938,0.113758,0.700459,0.120830,0.649803,26.836009
4,TESCO PLC,233.35,-10114000,A+,17.839379,17.812481,17.947215,44862000,2.73,-12.61,-2.00,4.73,4.75,0.07,0.122337,0.729543,0.024941,0.662263,0.029028,0.663773,22.544693

In [249]:
# make average of all years
df["Size"] = df[["Size 2017", "Size 2016", "Size 2015"]].mean(axis=1)
df["Asset Tangability"] = df[["Asset Tangability 2017", "Asset Tangability 2016", "Asset Tangability 2015"]].mean(axis=1)
df["Growth Opportunities"] = df[["Growth Opportunities 2017", "Growth Opportunities 2016", "Growth Opportunities 2015"]].mean(axis=1)
df["Profitability"] = df[["Profitability 2017", "Profitability 2016", "Profitability 2015"]].mean(axis=1)
df["NDTS"] = df[["NDTS 2017", "NDTS 2016", "NDTS 2015"]].mean(axis=1)
df.head()

,Company name,Gearing 2018,Long Term Debt 2018,BvD Independence Indicator,Size 2017,Size 2016,Size 2015,Total Assets 2018,Growth Opportunities 2017,Growth Opportunities 2016,Growth Opportunities 2015,Profitability 2017,Profitability 2016,Profitability 2015,NDTS 2015,Asset Tangability 2015,NDTS 2016,Asset Tangability 2016,NDTS 2017,Asset Tangability 2017,Gearing Long,Size,Asset Tangability,Growth Opportunities,Profitability,NDTS
0,BP P.L.C.,120.95,-44221000,B+,19.013328,18.834412,18.832671,216474000,19.59,0.17,-33.41,10.65,7.16,9.93,0.062929,0.727598,0.046101,0.741892,0.059610,0.724731,20.427857,18.893470,0.731407,-4.550000,9.246667,0.056213
1,ROYAL DUTCH SHELL PLC,65.28,-52265000,A+,19.256364,19.086189,19.005552,308106000,18.55,8.40,-33.54,15.52,14.08,10.86,0.076793,0.721978,0.057996,0.788762,0.060981,0.764025,16.963318,19.116035,0.758255,-2.196667,13.486667,0.065257
2,GLENCORE PLC,113.59,-20708000,A+,18.839108,18.635510,18.564686,100840000,22.58,7.34,-18.54,6.88,5.15,3.07,0.090174,0.671569,0.054570,0.651586,0.036340,0.633272,20.535502,18.679768,0.652142,3.793333,5.033333,0.060361
3,JACK RICHARDS HOLDINGS LIMITED,148.19,-11653,D,10.735766,10.615923,10.482430,43423,12.73,14.28,5.02,13.08,13.84,14.32,0.106400,0.678938,0.113758,0.700459,0.120830,0.649803,26.836009,10.611373,0.676400,10.676667,13.746667,0.113663
4,TESCO PLC,233.35,-10114000,A+,17.839379,17.812481,17.947215,44862000,2.73,-12.61,-2.00,4.73,4.75,0.07,0.122337,0.729543,0.024941,0.662263,0.029028,0.663773,22.544693,17.866358,0.685193,-3.960000,3.183333,0.058768

In [250]:
df["BvD Independence Indicator"].value_counts()

D     7350
B+    1829
U     1295
A+     881
A-     338
C      119
C+      24
B-       8
A        5
-        3
Name: BvD Independence Indicator, dtype: int64

In [251]:
pd.set_option('display.max_columns', None)
df.drop(df[(df["BvD Independence Indicator"] == "-") | (df["BvD Independence Indicator"] == "U")].index, axis=0, inplace=True)
df.head()

,Company name,Gearing 2018,Long Term Debt 2018,BvD Independence Indicator,Size 2017,Size 2016,Size 2015,Total Assets 2018,Growth Opportunities 2017,Growth Opportunities 2016,Growth Opportunities 2015,Profitability 2017,Profitability 2016,Profitability 2015,NDTS 2015,Asset Tangability 2015,NDTS 2016,Asset Tangability 2016,NDTS 2017,Asset Tangability 2017,Gearing Long,Size,Asset Tangability,Growth Opportunities,Profitability,NDTS
0,BP P.L.C.,120.95,-44221000,B+,19.013328,18.834412,18.832671,216474000,19.59,0.17,-33.41,10.65,7.16,9.93,0.062929,0.727598,0.046101,0.741892,0.059610,0.724731,20.427857,18.893470,0.731407,-4.550000,9.246667,0.056213
1,ROYAL DUTCH SHELL PLC,65.28,-52265000,A+,19.256364,19.086189,19.005552,308106000,18.55,8.40,-33.54,15.52,14.08,10.86,0.076793,0.721978,0.057996,0.788762,0.060981,0.764025,16.963318,19.116035,0.758255,-2.196667,13.486667,0.065257
2,GLENCORE PLC,113.59,-20708000,A+,18.839108,18.635510,18.564686,100840000,22.58,7.34,-18.54,6.88,5.15,3.07,0.090174,0.671569,0.054570,0.651586,0.036340,0.633272,20.535502,18.679768,0.652142,3.793333,5.033333,0.060361
3,JACK RICHARDS HOLDINGS LIMITED,148.19,-11653,D,10.735766,10.615923,10.482430,43423,12.73,14.28,5.02,13.08,13.84,14.32,0.106400,0.678938,0.113758,0.700459,0.120830,0.649803,26.836009,10.611373,0.676400,10.676667,13.746667,0.113663
4,TESCO PLC,233.35,-10114000,A+,17.839379,17.812481,17.947215,44862000,2.73,-12.61,-2.00,4.73,4.75,0.07,0.122337,0.729543,0.024941,0.662263,0.029028,0.663773,22.544693,17.866358,0.685193,-3.960000,3.183333,0.058768

In [252]:
df["BvD Independence Indicator"].value_counts()

D     7350
B+    1829
A+     881
A-     338
C      119
C+      24
B-       8
A        5
Name: BvD Independence Indicator, dtype: int64

In [253]:
# Save whole dataframe for analysis.
df.to_csv('./CleanData.csv', index=False)

# Save dataframe for regression.
regression_df = df[[
    "Company name",
    "Gearing 2018",
    "Gearing Long", 
    "BvD Independence Indicator",
    "Asset Tangability", 
    "Size", 
    "Growth Opportunities", 
    "Profitability", 
    "NDTS"
    ]]
# Drop outliers perhaps?
#regression_df = regression_df[regression_df["TobinsQ"] < 15]

regression_df["Ownership_Concentrated"] = regression_df["BvD Independence Indicator"].map({
    "A+": 0, "A-": 0, "A": 0,
    "B+": 0, "B-": 0, "B": 0,
    "C+": 1, "C-": 1, "C": 1,
    "D+": 1, "D-": 1, "D": 1,
})

regression_df.drop(["BvD Independence Indicator"], axis=1, inplace=True)


regression_df.rename(columns={
    'Gearing 2018': 'Gearing',
    "Asset Tangability": "Asset_Tangability",
    "Growth Opportunities": "Growth_Opportunities",
    "NDTS": "Non_Debt_Tax_Shields",
    }, inplace=True)

# replace spaces in column names with underscores.
regression_df.columns = [col.replace(" ", "_") for col in regression_df.columns]
regression_df.set_index("Company_name", inplace=True)
regression_df.head()

C:\Users\natha\AppData\Local\Temp/ipykernel_19004/4220794324.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regression_df["Ownership_Concentrated"] = regression_df["BvD Independence Indicator"].map({
c:\Venv\DataScience\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
c:\Venv\DataScience\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Gearing,Gearing_Long,Asset_Tangability,Size,Growth_Opportunities,Profitability,Non_Debt_Tax_Shields,Ownership_Concentrated
Company_name,,,,,,,,
BP P.L.C.,120.95,20.427857,0.731407,18.893470,-4.550000,9.246667,0.056213,0
ROYAL DUTCH SHELL PLC,65.28,16.963318,0.758255,19.116035,-2.196667,13.486667,0.065257,0
GLENCORE PLC,113.59,20.535502,0.652142,18.679768,3.793333,5.033333,0.060361,0
JACK RICHARDS HOLDINGS LIMITED,148.19,26.836009,0.676400,10.611373,10.676667,13.746667,0.113663,1
TESCO PLC,233.35,22.544693,0.685193,17.866358,-3.960000,3.183333,0.058768,0

In [254]:
regression_df.describe()

,Gearing,Gearing_Long,Asset_Tangability,Size,Growth_Opportunities,Profitability,Non_Debt_Tax_Shields,Ownership_Concentrated
count,10554.000000,10554.000000,10554.000000,10554.000000,10554.000000,10554.000000,10554.000000,10554.000000
mean,108.309200,14.434786,0.441534,10.063155,9.401275,13.068263,0.035191,0.709968
std,137.075647,15.731568,0.278177,1.502272,19.673241,14.999354,0.034278,0.453798
min,0.010000,0.000000,0.000166,4.446550,-53.810000,-71.170000,-0.081871,0.000000
25%,24.630000,2.313331,0.207741,9.224541,1.391667,4.497500,0.012473,0.000000
50%,60.675000,8.708128,0.406119,9.825608,6.340000,8.813333,0.025267,1.000000
75%,135.487500,21.263270,0.667281,10.706202,13.205833,16.225833,0.046031,1.000000
max,996.150000,86.611099,0.999916,19.116035,396.526667,99.616667,0.440056,1.000000

In [255]:
# Windorise Independent Variables.
drop_idx = []
pct = 2.5
for col in regression_df.columns:
    print(col)
    # get values above top and bottom pct.
    top = regression_df[col].quantile(1 - pct/100)
    bottom = regression_df[col].quantile(pct/100)
    # add indexes of rows that are above top and below bottom to drop_idx.
    drop_idx += list(regression_df[(regression_df[col] > top) | (regression_df[col] < bottom)].index)

drop_idx = list(set(drop_idx))
# Drop rows with outliers.
regression_df.drop(drop_idx, axis=0, inplace=True)

Gearing
Gearing_Long
Asset_Tangability
Size
Growth_Opportunities
Profitability
The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.Non_Debt_Tax_Shields

Ownership_Concentrated

c:\Venv\DataScience\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [256]:
regression_df.describe()

,Gearing,Gearing_Long,Asset_Tangability,Size,Growth_Opportunities,Profitability,Non_Debt_Tax_Shields,Ownership_Concentrated
count,7854.000000,7854.000000,7854.000000,7854.000000,7854.000000,7854.000000,7854.000000,7854.000000
mean,86.802851,12.458185,0.419381,10.035779,8.067765,10.723697,0.034359,0.702190
std,89.788815,12.582442,0.251388,1.153205,9.544867,9.050978,0.026495,0.457325
min,2.720000,0.078319,0.024471,7.501241,-12.116667,-0.423333,0.000941,0.000000
25%,24.950000,2.583509,0.212813,9.293902,1.806667,4.496667,0.014473,0.000000
50%,56.190000,8.124690,0.384555,9.832101,6.481667,8.215000,0.027035,1.000000
75%,115.660000,18.267742,0.610271,10.622564,12.733333,14.020833,0.046457,1.000000
max,524.210000,56.166896,0.946937,13.816424,45.883333,60.193333,0.129283,1.000000

In [257]:
regression_df.to_csv('./RegressionData.csv', index=False)